server {
    # Gzip Settings
    gzip on;
    gzip_disable "msie6";
    gzip_vary on;
    gzip_proxied any;
    gzip_types text/plain text/css application/json application/x-javascript application/javascript text/xml application/xml application/xml+rss text/javascript;

    # Brotli Settings
    brotli on;
    brotli_comp_level 4;
    brotli_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;

    listen 80;

    client_max_body_size 0;

    # TODO: @JOEL MACH DI GO SERVICE DO:
    # location /api/ {
    #     include /etc/nginx/proxy.conf;
    #     proxy_pass http://dev_backend:8000/api/;
    # }

    location / {
        include /etc/nginx/proxy.conf;
        proxy_pass http://dev_frontend:3000/;
    }

    error_page   500 502 503 504  /50x.html;

    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
